name: TitleApi
main: com.relicum.titleapi.TitleApi
author: Relicum
version: ${project.version}
description: Title Api for displaying Titles and Tabs
commands:
  testholder:
    description: Used to test out place holders
    usage: /<command> [type] [placeholder]
    default: op
  testbar:
    description: Test actionbar
    usage: /<command>
    default: op
  testtab:
    description: Test tab
    usage: /<command>
    default: op
